name = "nitro-deployment"
type = "javascript"
account_id = "8ea39dfb7bb411de7fcff5444d7a5dbb"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-09-10"
main=".output/server/index.mjs"

[site]
bucket = "./.output/public"

[build]
command = "true"
upload.format = "service-worker"
