name: cloudflare

on:
  push:
    branches:
      - main
      - cloudflare

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          NITRO_PRESET: cloudflare
      - uses: cloudflare/wrangler-action@v3.4.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
      - name: Test deployed site
        run: pnpm test:deployment
        env:
          DEPLOYMENT_URL: https://nitro-deployment.pi0.workers.dev/
