name: e2e

on:
  workflow_dispatch:
    inputs:
      url:
        required: false
        description: The URL to run the test suite against. If omitted, it runs against all.
        type: string
  deployment_status:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install
      - run: yarn test
        env:
          DEPLOYMENT_URL: ${{ github.event.inputs.url || github.event.deployment.url }}
