name: Firebase

on:
  push:
    branches:
      - main
      - firebase

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install
      - run: yarn build
        env:
          NITRO_PRESET: firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v11.16.0
        with:
          args: deploy --project nitro-deployment
        env:
          GCP_SA_KEY: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NITRO_DEPLOYMENT }}"
      - name: Test deployed site
        run: yarn test
        env:
          DEPLOYMENT_URL: https://nitro-deployment.web.app/
