name: firebase

on:
  push:
    branches:
      - main
      - firebase

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          NITRO_PRESET: firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v11.22.0
        with:
          args: deploy --project nitro-deployment
        env:
          GCP_SA_KEY: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NITRO_DEPLOYMENT }}"
      - name: Test deployed site
        run: pnpm test
        env:
          DEPLOYMENT_URL: https://nitro-deployment.web.app/
