name: lagon

on:
  push:
    branches:
      - main
      - lagon

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          NITRO_PRESET: lagon
      - name: Lagon deploy
        uses: lagonapp/github-action@latest
        if: github.ref == 'refs/heads/main'
        with:
          lagon_token: ${{ secrets.LAGON_TOKEN }}
          config: |
            {
              "function_id": "cleoau1wk0000mj0843yvsgi7",
              "organization_id": "cleeepy2j0006jx08ew36ivpg",
              "index": ".output/server/index.mjs",
              "client": null,
              "assets": ".output/public"
            }
      - name: Log Function URL
        run: |
          url=$(grep -o 'https://[^[:space:]]*' lagon.output)
          echo "Function available at: $url"
